# Generated by Django 4.2.6 on 2023-10-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='register',
        ),
    ]
