# Generated by Django 4.2.6 on 2023-10-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sapp.dept'),
        ),
        migrations.AddField(
            model_name='order',
            name='nam',
            field=models.CharField(default='Some Default Value', max_length=250),
        ),
    ]
